<?php

namespace Ydzy\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * pagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pagesRepository extends EntityRepository
{
	public function findListByType($type)
	{
		$query = $this->getEntityManager()
		->createQuery("
			SELECT p FROM ydzyAPIBundle:pages p
			WHERE p.name like :type
				and p.status = 0")->setParameter('type', $type."%");
		try {
			$pages = $query->getResult();
			return $pages;
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
	
	public function findMaxIdByType($type)
	{
		$query = $this->getEntityManager()->createQuery('SELECT p FROM YdzyApiBundle:pages p ORDER BY p.id DESC');
		try {

			$page = $query->getResult();
			return $type.($page[0]->getId() + 1);
		} catch (\Doctrine\ORM\NoResultException $e) {
			return $type.'1';
		}
		
	}
	
	public function findlpsyList()
	{
		$query = $this->getEntityManager()->createQuery('
			SELECT p.title,p.name, p.content,p.createDate FROM YdzyApiBundle:pages p JOIN ydzyAPIBundle:navlinks n WHERE n.num = p.name'
		)->getResult();
		return ($query);
		try {
			$pages = $query->getResult();
			return $pages;
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}
